# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LaboratoryV1' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  pod 'react-native-idfa',  path: '../node_modules/react-native-idfa'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaboratoryV1

  

  platform :ios, '9.0'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'LaboratoryV1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LaboratoryV1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaboratoryV1-tvOS

  target 'LaboratoryV1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
